version: "3.9"
services:

  CSharp:
    container_name: csdotnet
    image: mcr.microsoft.com/devcontainers/dotnet:latest
    volumes:
      - ../workspace:/workspace
    working_dir: /workspace
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: bash -c "sudo apt update && while sleep 1000; do :; done"
    tty: true
    stdin_open: true
