/*
 * This source file was generated by the Gradle 'init' task
 */
package refactoring1st;

public class App {
    public static final Movie REMBO = new Movie("Rembo", 0);
    public static final Movie LOTR = new Movie("Lord of the Rings", 1);
    public static final Movie HARRY_POTTER = new Movie("Harry Potter", 2);
    /* 
    public static final Movie REMBO = new Movie("Rembo", REGULAR);
    public static final Movie LOTR = new Movie("Lord of the Rings", NEW_RELEASE);
    public static final Movie HARRY_POTTER = new Movie("Harry Potter", CHILDRENS);
    */

    public static void main(String[] args) {
        Customer coustomer = new Customer("Hiroshi");
        coustomer.addRental(new Rental(REMBO, 1));
        coustomer.addRental(new Rental(LOTR, 4));
        coustomer.addRental(new Rental(HARRY_POTTER, 5));

        System.out.println(coustomer.statement());
    }
}
