/*
 * This source file was generated by the Gradle 'init' task
 */
package refactoring1st;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void statement() {
        String message = "Rental Record for Hiroshi\n" +
            "\tRembo\t2.0\n" +
            "\tLord of the Rings\t12.0\n" +
            "\tHarry Potter\t4.5\n" +
            "Amount owed is 18.5\n" +
            "You earned 4 frequent renter points";
        
            String htmlMessage = "<H1>Rental Record for <EM>Hiroshi</EM></H1><P>\n" +
            "Rembo: 2.0<BR>\n" +
            "Lord of the Rings: 12.0<BR>\n" +
            "Harry Potter: 4.5<BR>\n" +
            "<P>You owed <EM>18.5</EM><P>\n" +
            "On this rental you earned <EM>4</EM> frequent renter points<P>";


        Movie REMBO = new Movie("Rembo", 0);
        Movie LOTR = new Movie("Lord of the Rings", 1);
        Movie HARRY_POTTER = new Movie("Harry Potter", 2);

        Customer coustomer = new Customer("Hiroshi");
        coustomer.addRental(new Rental(REMBO, 1));
        coustomer.addRental(new Rental(LOTR, 4));
        coustomer.addRental(new Rental(HARRY_POTTER, 5));

        //assertNotEquals(coustomer.statement(), message);
        assertEquals(coustomer.statement(), message);
        assertEquals(coustomer.htmlStatement(), htmlMessage);
    }
}