/*
 * This source file was generated by the Gradle 'init' task
 */
package refactoring1st;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void statement() {
        String message = "Rental Record for Hiroshi\n" +
            "\tRembo\t2.0\n" +
            "\tLord of the Rings\t12.0\n" +
            "\tHarry Potter\t4.5\n" +
            "Amount owed is 18.5\n" +
            "You earned 4 frequent renter points";


        Movie REMBO = new Movie("Rembo", 0);
        Movie LOTR = new Movie("Lord of the Rings", 1);
        Movie HARRY_POTTER = new Movie("Harry Potter", 2);

        Customer coustomer = new Customer("Hiroshi");
        coustomer.addRental(new Rental(REMBO, 1));
        coustomer.addRental(new Rental(LOTR, 4));
        coustomer.addRental(new Rental(HARRY_POTTER, 5));

        //assertNotEquals(coustomer.statement(), message);
        assertEquals(coustomer.statement(), message);
    }
}
